config/routes.rb
Rails.application.routes.draw do
  get 'snapshorts/(index)' => 'snapshorts#index', as: :snapshorts
  get 'snapshorts/daily(/:user_id)' => 'snapshorts#daily', as: :snapshort

  root 'welcome#index'

end

app/models/snapshort.rb
class Snapshort < Hashie::Mash
end

app/controllers/snapshorts_controller.rb
require 'mathn'

class SnapshortsController < ApplicationController
    layout false, only: [:daily]

    def index
        @users = Hashie::Mash.new User.new(@users).extend(UserRepresenter).to_hash
    end

    def show
    end

    def daily
        if params[:user_id].present? && !params[:user_id].to_i.zero?
            @data         = Es.new
            @from         = Es::FROMDUMMY
            user_id       = params[:user_id].to_i
            @result       = @data.fetch_data(user_id)
            @assign_to_me = @data.assign_to_me(user_id)
            @assign_by_me = @data.assign_by_me(user_id)
            @my_todo      = @data.my_todo(user_id)
            @following    = @data.following(user_id)
        else
            render nothing: true
        end
        # byebug
        # SnapshortNotifier.daily_snapshort('user@example.com', 'Daily Snapshort', @result).deliver
    end
end

app/helpers/snapshorts_helper.rb
module SnapshortsHelper
end

app/views/snapshorts/_archievement.html.erb
<h2 style="font-size: 14px; font-family: helvetica; color:#3d4955; margin: 20px 0 25px; font-weight: normal;"><b>Month-to-Date Achievement</b></h2>
<table>
	<tr>
		<td valign="top" style="padding: 10px 35px 0 0;">
			<table cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td>
						<img src="http://static.taskworld.com/images/tw-clock.png" width="85" height="85" style="display: block;"/>
					</td>
					<td valign="top">
						<span style="font-size: 20px; font-family: helvetica;color:#83959d; display: block; padding: 5px 0 10px;"><%= number_to_percentage(@result.onTimeCompletion || 0, precision: 1) %></span>
						<span style="font-size: 12px; font-family: helvetica;color:#83959d; display: block; line-height: 13px;">On-time<br /> Completion (%)</span>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top" style="padding: 10px 35px 0 0;">
			<table cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td>
						<img src="http://static.taskworld.com/images/tw-star.png"  width="85" height="85"  style="display: block;"/></td>
					</td>
					<td valign="top">
						<span style="font-size: 20px; font-family: helvetica;color:#83959d; display: block; padding: 5px 0 10px;"><%= number_with_precision(@result.startRate || 0, precision: 1) %></span>
						<span style="font-size: 12px; font-family: helvetica;color:#83959d; display: block; line-height: 13px;">Star<br /> Rating (1-5)</span>
					</td>
				</tr>
			</table>
		</td>
		<td valign="top">
			<table cellpadding="0" cellspacing="0" border="0" width="200" align="right" style="font-size: 12px; font-family: helvetica; color:#3d4955;">
				<tr>
					<td>On-time</td>
					<td align="right"><%= number_with_delimiter(@result.onTime || 0) %></td>
				</tr>
				<tr>
					<td colspan="2" style="border-top:1px solid #ccd7df;">&nbsp;</td>
				</tr>
				<tr>
					<td>Overdue</td>
					<td align="right"><%= number_with_delimiter(@result.overDue || 0) %></td>
				</tr>
				<tr>
					<td colspan="2" style="border-top:1px solid #ccd7df;">&nbsp;</td>
				</tr>
				<tr>
					<td>No Target Date</td>
					<td align="right"><%= number_with_delimiter(@result.noTargetDate || 0) %></td>
				</tr>
				<tr>
					<td colspan="2" style="border-top:1px solid #ccd7df;">&nbsp;</td>
				</tr>
				<tr>
					<td><b style="font-size: 14px;">Total Closed Tasks</b></td>
					<td align="right"><b style="font-size: 14px;"><%= number_with_delimiter(@result.closedTask || 0) %></b></td>
				</tr>
				<tr>
					<td colspan="2" align="right" style="padding: 22px 0 0"><a href="//taskworld.com/dashboard#"><img src="http://static.taskworld.com/images/tw-button-go2dashboard.gif" alt="Go to Dashboard" width="122" height="23" border="0" /></a></td>
				</tr>
			</table>
		</td>
	</tr>
</table>

app/views/snapshorts/_assign_by_me.html.erb
<h2 style="font-size: 14px; font-family: helvetica; color:#3d4955; font-weight: normal;"><b>Assigned By Me</b></h2>

<table cellpadding="0" cellspacing="0" border="0" width="100%" style="color: #ffffff; font-size: 13px; font-family: helvetica;">
	<tr>
		<td style="background-color: #ea5050; border: 1px solid #ea5050;" width="206">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">Overdue</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">100</td>
				</tr>
			</table>
		</td>
		<td style="background-color: #3cbaeb; border-top: 1px solid #3cbaeb; border-bottom: 1px solid #3cbaeb;" width="208">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">Completed</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">200</td>
				</tr>
			</table>
		</td>
		<td style="background-color: #3dc178; border: 1px solid #3dc178;" width="206">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">In Progress</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">300</td>
				</tr>
			</table>
		</td>
	</tr>
</table><br />

<table cellpadding="0" cellspacing="0" border="0" width="620" style="background-color: #ffffff; border: 1px solid #e8ebec; border-bottom: 0;
font-size: 13px; font-family: helvetica;"
>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a fringilla arcu. Nulla facilisi. Suspendisse lacus enim, feugiat sit amet lectus non, feugiat scelerisque mauris. Quisque at neque eget purus interdum mattis. Sed mauris felis, interdum eget mi et, consectetur cursus erat. Aliquam semper auctor mauris et tempus. Ut dictum vestibulum neque sed porta. Nulla rutrum bibendum diam nec ultricies. Cras porta consequat tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce rhoncus nulla nec pharetra commodo. Sed quis vestibulum nunc. Aliquam non fermentum sem. Aenean eu convallis magna, a dictum orci. Nulla facilisi. Etiam vestibulum porta velit, eget eleifend lectus aliquam ut.</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #ea5050; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #ea5050; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a fringilla arcu. Nulla facilisi. Suspendisse lacus enim, feugiat sit amet lectus non, feugiat scelerisque mauris. Quisque at neque eget purus interdum mattis. Sed mauris felis, interdum eget mi et, consectetur cursus erat.</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #6dcff6; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #6dcff6; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a fringilla arcu. Nulla facilisi. Suspendisse lacus enim, feugiat sit amet lectus non, feugiat scelerisque mauris. </a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #00ca7b; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #00ca7b; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
</table>
<table cellpadding="0" cellspacing="0" border="0" width="620">
	<tr>
		<td align="right" style="background-color: #f0f3f4;">
			<a href="//taskworld.com/task#byme?status=active"><img src="http://static.taskworld.com/images/tw-button-view-all2.gif" alt="View All" width="75" height="23" border="0" /></a>
		</td>
	</tr>
</table>

app/views/snapshorts/_assign_to_me.html.erb
<h2 style="font-size: 14px; font-family: helvetica; color:#3d4955; font-weight: normal;"><b>Assigned To Me</b></h2>

<table cellpadding="0" cellspacing="0" border="0" width="100%" style="color: #ffffff; font-size: 13px; font-family: helvetica;">
	<tr>
		<td style="background-color: #ea5050; border: 1px solid #ea5050;" width="206">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">
						<a href="//taskworld.com/task#tome?status=overdue" style="color: #ffffff; text-decoration:none;">Overdue</a>
					</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">
						<a href="//taskworld.com/task#tome?status=overdue" style="color: #ffffff; text-decoration:none;"><%= @assign_to_me.overdue.hits.total %></a>
					</td>
				</tr>
			</table>
		</td>
		<td style="background-color: #3cbaeb; border-top: 1px solid #3cbaeb; border-bottom: 1px solid #3cbaeb;" width="208">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">
						<a href="//taskworld.com/task#tome?status=completed" style="color: #ffffff; text-decoration:none;">Completed</a>
					</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">
						<a href="//taskworld.com/task#tome?status=completed" style="color: #ffffff; text-decoration:none;"><%= @assign_to_me.completed.hits.total %></a>
					</td>
				</tr>
			</table>
		</td>
		<td style="background-color: #3dc178; border: 1px solid #3dc178;" width="206">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">
						<a href="//taskworld.com/task#tome?status=inprogress" style="color: #ffffff; text-decoration:none;">In Progress</a>
					</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">
						<a href="//taskworld.com/task#tome?status=inprogress" style="color: #ffffff; text-decoration:none;"><%= @assign_to_me.inprogress.hits.total %></a>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table><br />

<table cellpadding="0" cellspacing="0" border="0" width="620" style="background-color: #ffffff; border: 1px solid #e8ebec; border-bottom: 0;
font-size: 13px; font-family: helvetica;"
>
	<% @assign_to_me.overdue.hits.hits.each do |task| %>
	<% variance_day = distance_of_time_in_words(task._source.estimatedDueDate.to_datetime, @from) %>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<%= link_to task._source.subject, "//taskworld.com/task#id/#{task._source.id}", style: "text-decoration: none; color:#3d4955" %>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #ea5050; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;"><%= variance_day %></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<% end %>

	<% @assign_to_me.completed.hits.hits.each do |task| %>
	<% variance_day = distance_of_time_in_words(task._source.estimatedDueDate.to_datetime, task._source.completedDate.to_datetime) %>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<%= link_to task._source.subject, "//taskworld.com/task#id/#{task._source.id}", style: "text-decoration: none; color:#3d4955" %>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #6dcff6; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;"><%= variance_day %></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<% end %>

	<% @assign_to_me.inprogress.hits.hits.each do |task| %>
	<% variance_day = distance_of_time_in_words(task._source.estimatedDueDate.to_datetime, @from) %>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<%= link_to task._source.subject, "//taskworld.com/task#id/#{task._source.id}", style: "text-decoration: none; color:#3d4955" %>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #00ca7b; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;"><%= variance_day %></td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<% end %>
</table>
<table cellpadding="0" cellspacing="0" border="0" width="620">
	<tr>
		<td align="right" style="background-color: #f0f3f4;">
			<a href="//taskworld.com/task#tome?status=active"><img src="http://static.taskworld.com/images/tw-button-view-all1.gif" alt="View All" width="75" height="23" border="0" /></a>
		</td>
	</tr>
</table>

app/views/snapshorts/_my_todo.html.erb
<h2 style="font-size: 14px; font-family: helvetica; color:#3d4955; font-weight: normal;"><b>My To-Do</b></h2>

<table cellpadding="0" cellspacing="0" border="0" width="100%" style="color: #ffffff; font-size: 13px; font-family: helvetica;">
	<tr>
		<td style="background-color: #ea5050; border: 1px solid #ea5050;" width="206">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">Overdue</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">100</td>
				</tr>
			</table>
		</td>
		<td style="background-color: #3cbaeb; border-top: 1px solid #3cbaeb; border-bottom: 1px solid #3cbaeb;" width="208">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">Completed</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">200</td>
				</tr>
			</table>
		</td>
		<td style="background-color: #3dc178; border: 1px solid #3dc178;" width="206">
			<table cellpadding="5" cellspacing="0" border="0" width="180" align="center">
				<tr>
					<td style="color: #ffffff; font-family: helvetica;">In Progress</td>
					<td align="right" style="font-size: 18px; font-family: helvetica; color: #ffffff;">300</td>
				</tr>
			</table>
		</td>
	</tr>
</table><br />

<table cellpadding="0" cellspacing="0" border="0" width="620" style="background-color: #ffffff; border: 1px solid #e8ebec; border-bottom: 0;
font-size: 13px; font-family: helvetica;"
>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a fringilla arcu. Nulla facilisi. Suspendisse lacus enim, feugiat sit amet lectus non, feugiat scelerisque mauris. Quisque at neque eget purus interdum mattis. Sed mauris felis, interdum eget mi et, consectetur cursus erat. Aliquam semper auctor mauris et tempus. Ut dictum vestibulum neque sed porta. Nulla rutrum bibendum diam nec ultricies. Cras porta consequat tincidunt. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce rhoncus nulla nec pharetra commodo. Sed quis vestibulum nunc. Aliquam non fermentum sem. Aenean eu convallis magna, a dictum orci. Nulla facilisi. Etiam vestibulum porta velit, eget eleifend lectus aliquam ut.</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #ea5050; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #ea5050; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a fringilla arcu. Nulla facilisi. Suspendisse lacus enim, feugiat sit amet lectus non, feugiat scelerisque mauris. Quisque at neque eget purus interdum mattis. Sed mauris felis, interdum eget mi et, consectetur cursus erat.</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #6dcff6; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #6dcff6; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a fringilla arcu. Nulla facilisi. Suspendisse lacus enim, feugiat sit amet lectus non, feugiat scelerisque mauris. </a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #00ca7b; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
	<tr>
		<td style="padding: 6px 6px 6px 10px;" valign="top">
			<a href="#" style="text-decoration: none; color:#3d4955">Lorem ipsum dolor sit amet</a>
		</td>
		<td style="padding:4px;" width="35" align="right" valign="top">
			<table style="background-color: #00ca7b; color: #ffffff; width:35px;">
				<tr>
					<td align="right" style="font-size: 13px; font-family: helvetica;">5d</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2" style="height:1px; background-color:#e8ebec; font-size:1; line-height:1px;">&nbsp;</td>
	</tr>
</table>
<table cellpadding="0" cellspacing="0" border="0" width="620">
	<tr>
		<td align="right" style="background-color: #f0f3f4;">
			<a href="//taskworld.com/task#todo?status=active"><img src="http://static.taskworld.com/images/tw-button-view-all3.gif" alt="View All"  width="75" height="23" border="0" /></a>
		</td>
	</tr>
</table>

app/views/snapshorts/index.html.erb
<h1>Snapshorts#index</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.hits.hits.each do |user| %>
      <% next unless user._source.userId %>
      <tr>
        <td><%= user._source.userId %></td>
        <td><%= user._source.firstName %></td>
        <td><%= user._source.lastName %></td>
        <td><%= user._source.email %></td>
        <td><%= link_to "Daily Snapshort", snapshort_path(user._source.userId), class: 'btn btn-success' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/snapshorts/show.html.erb
<h1>Snapshorts#show</h1>